# Generated by Django 4.0.5 on 2022-06-29 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tom_targets', '0022_delete_targetclassification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(blank=True, default='')),
                ('level', models.TextField(blank=True, default='')),
                ('classification', models.TextField(blank=True, default='')),
                ('probability', models.FloatField(blank=True, null=True)),
                ('mjd', models.FloatField(blank=True, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom_targets.target')),
            ],
        ),
    ]
