# Generated by Django 4.0.5 on 2022-07-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_classifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetclassification',
            name='transient',
            field=models.BooleanField(default=False),
        ),
    ]
